services:
  backend:
    image: ecmartins/reciclaai-backend:latest
    container_name: reciclaai-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/apps/backend
    environment:
      - DATABASE_URL=sqlite:///./reciclaai.db

  frontend:
    image: ecmartins/reciclaai-frontend:latest
    container_name: reciclaai-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  backend_data:

