[project]
name = "reciclaa-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "ruff>=0.8.4",
    "matplotlib>=3.9.0",
    "tensorflow>=2.20.0",
    "uvicorn[standard]>=0.38.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "scipy>=1.16.3",
    "sqlalchemy>=2.0.36",
    "passlib[bcrypt]>=1.7.4",
    "python-jose[cryptography]>=3.3.0",
    "email-validator>=2.1.0",
    "bcrypt==4.1.3",
]

