[project]
name = "reciclaa-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "ruff>=0.8.4",
    "matplotlib>=3.9.0",
    "tensorflow>=2.20.0",
    "uvicorn[standard]>=0.38.0",
]

